name: 🐍 Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # Cada día a medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate the Snake Game from GitHub Contributions
        uses: Platane/snk@v3
        with:
          github_user_name: Rober160
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
